queue_rules:
  - name: main
    conditions:
      - base=main
      # Require integration tests before merging only
      - check-success=Cloudflare Pages
      - check-success=Lint and Test Snippets
      - check-success=Test the build 
pull_request_rules:
  - name: merge to master
    conditions:
      - label=automerge:merge
    actions:
      queue:
        name: main
        method: merge
  - name: rebase updates then merge to master
    conditions:
      - label=automerge:rebase
    actions:
      queue:
        name: main
        method: merge
        update_method: rebase
  - name: squash to master
    conditions:
      - label=automerge:squash
    actions:
      queue:
        name: main
        method: squash
