matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
    ignores:
    - code
    - pre
  sources:
  - 'main/.vuepress/dist/**/*.html'
  default_encoding: utf-8