matrix:
- name: html
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
    ignores:
    - :matches(code, pre)
    - .language-js
    - code
    - pre
    - pre .language-js
  sources:
  - 'main/.vuepress/dist/**/*.html'
  default_encoding: utf-8