sequenceDiagram
  autonumber

  actor V1 as Voter1

  participant WF as walletFactory
  participant Zoe
  participant Charter as swaparoo<br>charter

    V1-)WF: executeOffer({ id: 'v0-accept-charter',<br>{ invitationSpec: source: 'purse',<br>description: 'charter member invitation',<br>instance: swaparooCharter } })
    WF--)Zoe: offer(invitationQ1)
    Zoe--)Charter: charterMemberHandler()
    Charter--)WF: { invitationMakers: { VoteOnParamChange, ... } }
    WF--)V1: { payouts: {} }
