sequenceDiagram
  autonumber

  actor V1 as Voter1

  participant Core as swaparoo<br>deployer

  participant Zoe
  participant Ctee as swaparoo<br>committee

    Core-)Zoe: startInstance(committee, ...)
    Zoe--)Ctee: start({committeeSize: 1})
    Ctee--)Zoe: { creatorFacet, ... }
    Zoe--)Core: { creatorFacet, ... }
    Core--)Ctee: E(creatorFacet).getVoterInvitations()
    Ctee--)Core: [invitationV1]
    Core--)V1: invitationV1
