sequenceDiagram
  autonumber

  participant Core as swaparoo<br>deployer
  participant Zoe

  participant SG as swaparoo<br>governor
  participant S as swaparoo

    Core-)SG: startInstance(contractGovernor,<br>{ governedContractInstallation: swaparoo })
    SG--)S: startInstance(swaparoo)
    S--)SG: swaparooFacets
    SG--)Core: govFacets
    Core--)SG: E(govFacets.creatorFacet).getCreatorFacet()
    SG--)Core: swaparoo<br>limitedCreatorFacet
