sequenceDiagram
  actor client

  box aqua Cosmos SDK layer
  participant chain
  end

  box darksalmon Hardened JS VM
  participant chainStorage
  participant agoricNames
  end

    agoricNames->>chainStorage: E(root).makeChildNode('brand')
    chainStorage-->>agoricNames: brandNode
    agoricNames-->>chainStorage: E(invbrandNodeNode).setValue('...IST...')
    chainStorage->>chain: change(<br>'published.agoricNames.brand',<br> '...IST...')
    client->>chain: Data(<br>'published.agoricNames.brand')
    chain-->>client: '...IST...'
