sequenceDiagram
box darksalmon Zoe API (simplified)

  participant agent
  participant zoe
  participant contract
end

    agent->>+zoe: offer(invitation, {give, want}, pmts)
    zoe-->>agent: userSeat
    zoe->>+contract: {give, want}
    contract-->>-zoe: reallocate()
    agent->>zoe: E(userSeat).getPayouts()
    zoe-->>-agent: payout payments
