// SNAPIFI FEATURE TOGGLE SYSTEM
// Comprehensive feature management with granular control

export interface FeatureToggle {
  id: string
  name: string
  description: string
  category: string
  subcategory?: string
  enabled: boolean
  dependencies: string[]
  conflicts: string[]
  requiresRestart: boolean
  betaFeature: boolean
  premiumFeature: boolean
  estimatedImpact: "low" | "medium" | "high"
  lastModified: Date
  modifiedBy: string
}

export interface FeatureCategory {
  id: string
  name: string
  description: string
  icon: string
  color: string
  features: FeatureToggle[]
}

// COMPREHENSIVE FEATURE DEFINITIONS
export const SNAPIFI_FEATURE_TOGGLES: FeatureToggle[] = [
  // CRITICAL PRIORITY FEATURES
  {
    id: "system_backup_controls",
    name: "System Backup Controls",
    description: "Manual backup triggers and restore capabilities with automated scheduling",
    category: "System Infrastructure",
    subcategory: "Data Protection",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: true,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "legal_document_acceptance",
    name: "Legal Document Acceptance System",
    description: "Digital signature and legal document acceptance workflow with blockchain verification",
    category: "Legal & Compliance",
    subcategory: "Document Management",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // TRANSACTION MANAGEMENT
  {
    id: "advanced_transaction_filtering",
    name: "Advanced Transaction Filtering",
    description: "Comprehensive transaction filtering by category, date range, amount, and status",
    category: "Financial Management",
    subcategory: "Transactions",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "enhanced_transaction_filtering",
    name: "Enhanced Transaction Filtering",
    description: "Specialized filtering system with advanced search capabilities and saved filters",
    category: "Financial Management",
    subcategory: "Transactions",
    enabled: false,
    dependencies: ["advanced_transaction_filtering"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "transaction_sorting",
    name: "Transaction Sorting",
    description: "Multi-column sorting for transaction lists with custom sort orders",
    category: "Financial Management",
    subcategory: "Transactions",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "transaction_detail_modal",
    name: "Transaction Detail Modal",
    description: "Detailed transaction view with full audit trail and related information",
    category: "Financial Management",
    subcategory: "Transactions",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "real_time_transaction_updates",
    name: "Real-time Transaction Updates",
    description: "Live transaction updates with WebSocket connections",
    category: "Financial Management",
    subcategory: "Transactions",
    enabled: false,
    dependencies: ["websocket_support"],
    conflicts: [],
    requiresRestart: true,
    betaFeature: true,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // DATA MANAGEMENT & PAGINATION
  {
    id: "universal_pagination",
    name: "Universal Pagination System",
    description: "Comprehensive pagination system across all data tables",
    category: "Data Management",
    subcategory: "Pagination",
    enabled: false,
    dependencies: [],
    conflicts: ["infinite_scroll"],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "keyboard_navigation",
    name: "Keyboard Navigation",
    description: "Keyboard shortcuts for pagination navigation and accessibility",
    category: "Data Management",
    subcategory: "Accessibility",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "pagination_size_options",
    name: "Pagination Size Options",
    description: "Allow users to customize items per page (10, 25, 50, 100)",
    category: "Data Management",
    subcategory: "Pagination",
    enabled: false,
    dependencies: ["universal_pagination"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "pagination_analytics",
    name: "Pagination Analytics",
    description: "Track user pagination behavior and optimize page sizes",
    category: "Data Management",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["universal_pagination", "analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "infinite_scroll",
    name: "Infinite Scroll",
    description: "Alternative to pagination with infinite scroll for mobile optimization",
    category: "Data Management",
    subcategory: "Pagination",
    enabled: false,
    dependencies: [],
    conflicts: ["universal_pagination"],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "pagination_preloader",
    name: "Pagination Preloader",
    description: "Smooth loading states and skeleton screens for pagination",
    category: "Data Management",
    subcategory: "Performance",
    enabled: false,
    dependencies: ["universal_pagination"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "lazy_loading_optimization",
    name: "Lazy Loading Optimization",
    description: "Performance optimization with lazy loading for images, content, and components",
    category: "Data Management",
    subcategory: "Performance",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // HOLOGRAPHIC PRODUCTS & VISUALIZATION
  {
    id: "holographic_product_details",
    name: "Holographic Product Details",
    description: "Detailed product pages with holographic visualization and specifications",
    category: "Holographic Experience",
    subcategory: "Products",
    enabled: false,
    dependencies: ["3d_rendering_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_data_visualization",
    name: "Holographic Data Visualization",
    description: "Advanced 3D data visualization for product analytics and metrics",
    category: "Holographic Experience",
    subcategory: "Visualization",
    enabled: false,
    dependencies: ["3d_rendering_engine", "analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_product_comparison",
    name: "Holographic Product Comparison",
    description: "Side-by-side holographic product comparison with interactive features",
    category: "Holographic Experience",
    subcategory: "Products",
    enabled: false,
    dependencies: ["holographic_product_details"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_platform_metrics",
    name: "Holographic Platform Performance Metrics",
    description: "Real-time performance monitoring with holographic dashboards",
    category: "Holographic Experience",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["holographic_data_visualization"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_product_editor",
    name: "Holographic Product Editor",
    description: "Admin tool for creating and editing holographic product displays",
    category: "Holographic Experience",
    subcategory: "Admin Tools",
    enabled: false,
    dependencies: ["holographic_product_details"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_glass_cards",
    name: "Holographic Glass Cards",
    description: "Premium holographic glass card design for marketplace items",
    category: "Holographic Experience",
    subcategory: "UI Components",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_certification_levels",
    name: "Holographic Certification Levels",
    description: "Tiered certification system for holographic product quality",
    category: "Holographic Experience",
    subcategory: "Quality Assurance",
    enabled: false,
    dependencies: ["holographic_product_details"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_label_analytics",
    name: "Holographic Label Analytics",
    description: "Analytics for holographic label performance and user engagement",
    category: "Holographic Experience",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_animation_presets",
    name: "Holographic Animation Presets",
    description: "Pre-built animation templates for holographic displays",
    category: "Holographic Experience",
    subcategory: "Animations",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_sound_effects",
    name: "Holographic Sound Effects",
    description: "Audio enhancement for holographic product interactions",
    category: "Holographic Experience",
    subcategory: "Audio",
    enabled: false,
    dependencies: ["audio_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "holographic_animation_customization",
    name: "Holographic Animation Customization",
    description: "User-customizable animation settings for holographic elements",
    category: "Holographic Experience",
    subcategory: "Customization",
    enabled: false,
    dependencies: ["holographic_animation_presets"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // E-COMMERCE & MARKETPLACE
  {
    id: "product_comparison_tool",
    name: "Product Comparison Tool",
    description: "Comprehensive product comparison tool with detailed specifications",
    category: "E-Commerce",
    subcategory: "Products",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "wishlist_system",
    name: "Wishlist System",
    description: "User wishlist system with sharing and notification features",
    category: "E-Commerce",
    subcategory: "User Features",
    enabled: false,
    dependencies: ["user_accounts"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "quick_view_modal",
    name: "Quick View Modal",
    description: "Quick preview modal for products without leaving current page",
    category: "E-Commerce",
    subcategory: "UI Components",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "advanced_product_filters",
    name: "Advanced Product Filters",
    description: "Advanced filtering system with multiple criteria and saved filters",
    category: "E-Commerce",
    subcategory: "Search & Filter",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "ai_product_recommendations",
    name: "AI Product Recommendations",
    description: "AI-powered product recommendation engine based on user behavior",
    category: "E-Commerce",
    subcategory: "AI Features",
    enabled: false,
    dependencies: ["ai_engine", "user_analytics"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "product_image_zoom",
    name: "Product Image Zoom",
    description: "High-resolution image zoom functionality for product details",
    category: "E-Commerce",
    subcategory: "Media",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "product_image_gallery",
    name: "Product Image Gallery",
    description: "Multi-image gallery with thumbnails and slideshow functionality",
    category: "E-Commerce",
    subcategory: "Media",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "product_video_previews",
    name: "Product Video Previews",
    description: "Video preview functionality for products with video content",
    category: "E-Commerce",
    subcategory: "Media",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // AR/VR & IMMERSIVE FEATURES
  {
    id: "product_360_views",
    name: "360° Product Views",
    description: "Interactive 360-degree product visualization system",
    category: "AR/VR Experience",
    subcategory: "360° Views",
    enabled: false,
    dependencies: ["3d_rendering_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "ar_product_preview",
    name: "AR Product Preview",
    description: "Augmented reality product preview using device camera",
    category: "AR/VR Experience",
    subcategory: "Augmented Reality",
    enabled: false,
    dependencies: ["webxr_support", "camera_access"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "product_360_comparison",
    name: "360° Product Comparison",
    description: "Side-by-side 360-degree product comparison tool",
    category: "AR/VR Experience",
    subcategory: "360° Views",
    enabled: false,
    dependencies: ["product_360_views"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "product_annotations",
    name: "Product Annotations",
    description: "Interactive annotations and hotspots for 360° product views",
    category: "AR/VR Experience",
    subcategory: "Interactivity",
    enabled: false,
    dependencies: ["product_360_views"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "vr_compatibility",
    name: "VR Compatibility",
    description: "Virtual reality support for immersive product experiences",
    category: "AR/VR Experience",
    subcategory: "Virtual Reality",
    enabled: false,
    dependencies: ["webxr_support", "vr_headset_support"],
    conflicts: [],
    requiresRestart: true,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "product_360_analytics",
    name: "360° Analytics",
    description: "Analytics for 360° view engagement and user interaction patterns",
    category: "AR/VR Experience",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["product_360_views", "analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // REAL ESTATE & PROPERTY
  {
    id: "real_estate_marketplace",
    name: "Real Estate Marketplace",
    description: "Comprehensive real estate marketplace with property listings",
    category: "Real Estate",
    subcategory: "Marketplace",
    enabled: false,
    dependencies: ["mapping_service", "property_data_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "property_bidding_system",
    name: "Property Bidding System",
    description: "Bidding system for real estate properties with auction features",
    category: "Real Estate",
    subcategory: "Trading",
    enabled: false,
    dependencies: ["real_estate_marketplace", "payment_system"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "commercial_property_marketplace",
    name: "Commercial Property Marketplace",
    description: "Specialized marketplace for commercial real estate transactions",
    category: "Real Estate",
    subcategory: "Commercial",
    enabled: false,
    dependencies: ["real_estate_marketplace"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // AI & INTELLIGENT FEATURES
  {
    id: "ai_onboarding_experience",
    name: "AI Onboarding Experience",
    description: "Intelligent onboarding system with personalized user guidance",
    category: "AI Features",
    subcategory: "Onboarding",
    enabled: false,
    dependencies: ["ai_engine", "user_analytics"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "ai_chatbot_support",
    name: "AI Chatbot Support",
    description: "Intelligent chatbot for customer support and assistance",
    category: "AI Features",
    subcategory: "Support",
    enabled: false,
    dependencies: ["ai_engine", "nlp_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "predictive_analytics",
    name: "Predictive Analytics",
    description: "AI-powered predictive analytics for financial and market insights",
    category: "AI Features",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["ai_engine", "analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // LEGAL & COMPLIANCE
  {
    id: "multi_language_legal",
    name: "Multi-language Legal Documents",
    description: "Multi-language support for all legal documents and terms",
    category: "Legal & Compliance",
    subcategory: "Localization",
    enabled: false,
    dependencies: ["translation_service"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "quantum_legal_verification",
    name: "Quantum Legal Verification",
    description: "Advanced cryptographic verification for legal document integrity",
    category: "Legal & Compliance",
    subcategory: "Security",
    enabled: false,
    dependencies: ["quantum_crypto_engine"],
    conflicts: [],
    requiresRestart: true,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "legal_ai_assistant",
    name: "Legal AI Assistant",
    description: "AI-powered legal assistant for document review and compliance",
    category: "Legal & Compliance",
    subcategory: "AI Features",
    enabled: false,
    dependencies: ["ai_engine", "legal_database"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "legal_document_versioning",
    name: "Legal Document Versioning",
    description: "Version control system for legal documents with change tracking",
    category: "Legal & Compliance",
    subcategory: "Document Management",
    enabled: false,
    dependencies: ["legal_document_acceptance"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // UI/UX ENHANCEMENTS
  {
    id: "imperial_theme",
    name: "Imperial Theme",
    description: "Regal imperial design theme with classical elements",
    category: "UI/UX",
    subcategory: "Themes",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "imperial_product_cards",
    name: "Imperial Product Cards",
    description: "Redesign product cards with imperial/regal styling and animations",
    category: "UI/UX",
    subcategory: "Components",
    enabled: false,
    dependencies: ["imperial_theme"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "latin_interface_elements",
    name: "Latin Interface Elements",
    description: "Incorporate Latin text and classical design elements throughout UI",
    category: "UI/UX",
    subcategory: "Localization",
    enabled: false,
    dependencies: ["imperial_theme"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "enhanced_supreme_authority_coin",
    name: "Enhanced Supreme Authority Coin",
    description: "Advanced animations and interactions for Supreme Authority coin component",
    category: "UI/UX",
    subcategory: "Branding",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "imperial_sound_effects",
    name: "Imperial Sound Effects",
    description: "Audio feedback system with imperial-themed sound effects",
    category: "UI/UX",
    subcategory: "Audio",
    enabled: false,
    dependencies: ["audio_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "keyboard_shortcuts",
    name: "Keyboard Shortcuts",
    description: "Comprehensive keyboard shortcut system for power users",
    category: "UI/UX",
    subcategory: "Accessibility",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "touch_optimization",
    name: "Touch Optimization",
    description: "Mobile-optimized touch interface with gesture support",
    category: "UI/UX",
    subcategory: "Mobile",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "auto_hide_timer",
    name: "Auto-hide Timer",
    description: "Auto-hide functionality for UI elements with customizable timers",
    category: "UI/UX",
    subcategory: "Behavior",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "sticky_filters",
    name: "Sticky Filters",
    description: "Persistent filter states that remain active across sessions",
    category: "UI/UX",
    subcategory: "Behavior",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "hover_preview",
    name: "Hover Preview",
    description: "Quick preview functionality on hover for various UI elements",
    category: "UI/UX",
    subcategory: "Interactivity",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // INVESTMENT & FINANCIAL TOOLS
  {
    id: "investment_performance_charts",
    name: "Investment Performance Charts",
    description: "Comprehensive charting system for investment performance tracking",
    category: "Investment Tools",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["charting_library"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "portfolio_builder",
    name: "Portfolio Builder",
    description: "Interactive portfolio construction and management tool",
    category: "Investment Tools",
    subcategory: "Portfolio Management",
    enabled: false,
    dependencies: ["market_data_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "risk_assessment_tools",
    name: "Risk Assessment Tools",
    description: "Comprehensive risk analysis and assessment toolkit",
    category: "Investment Tools",
    subcategory: "Risk Management",
    enabled: false,
    dependencies: ["risk_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "investment_calculator",
    name: "Investment Calculator",
    description: "Advanced financial calculators for various investment scenarios",
    category: "Investment Tools",
    subcategory: "Calculators",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "real_time_market_data",
    name: "Real-time Market Data",
    description: "Live market data integration with real-time price feeds",
    category: "Investment Tools",
    subcategory: "Market Data",
  {
    id: "real_time_market_data",
    name: "Real-time Market Data",
    description: "Live market data integration with real-time price feeds",
    category: "Investment Tools",
    subcategory: "Market Data",
    enabled: false,
    dependencies: ["market_data_api", "websocket_support"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // GAMIFICATION & SOCIAL
  {
    id: "progression_ceremonies",
    name: "Progression Ceremonies",
    description: "Ceremonial events and animations for user progression milestones",
    category: "Gamification",
    subcategory: "Events",
    enabled: false,
    dependencies: ["progression_system"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "social_features",
    name: "Social Features",
    description: "Social networking features for user interaction and community",
    category: "Gamification",
    subcategory: "Social",
    enabled: false,
    dependencies: ["user_accounts", "messaging_system"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "seasonal_events",
    name: "Seasonal Events",
    description: "Time-limited seasonal events with special rewards and challenges",
    category: "Gamification",
    subcategory: "Events",
    enabled: false,
    dependencies: ["progression_system"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "progression_analytics",
    name: "Progression Analytics",
    description: "Analytics dashboard for tracking user progression and engagement",
    category: "Gamification",
    subcategory: "Analytics",
    enabled: false,
    dependencies: ["analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "mobile_app_integration",
    name: "Mobile App Integration",
    description: "Mobile app companion with gamification features and notifications",
    category: "Gamification",
    subcategory: "Mobile",
    enabled: false,
    dependencies: ["push_notifications"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // BUSINESS & ENTERPRISE
  {
    id: "business_credit_monitoring",
    name: "Business Credit Monitoring",
    description: "Business credit score monitoring and reporting system",
    category: "Business Features",
    subcategory: "Credit Management",
    enabled: false,
    dependencies: ["credit_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "business_compliance_tracking",
    name: "Business Compliance Tracking",
    description: "Automated compliance monitoring for business entities",
    category: "Business Features",
    subcategory: "Compliance",
    enabled: false,
    dependencies: ["compliance_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "business_partnership_benefits",
    name: "Business Partnership Benefits",
    description: "Partnership program with tiered benefits and rewards",
    category: "Business Features",
    subcategory: "Partnerships",
    enabled: false,
    dependencies: ["user_accounts"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "business_claims_processing",
    name: "Business Claims Processing",
    description: "Automated business insurance claims processing and management",
    category: "Business Features",
    subcategory: "Insurance",
    enabled: false,
    dependencies: ["insurance_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // ADMIN & SYSTEM ENHANCEMENTS
  {
    id: "real_time_admin_notifications",
    name: "Real-time Admin Notifications",
    description: "Live notification system for critical events and system alerts",
    category: "Admin System",
    subcategory: "Notifications",
    enabled: false,
    dependencies: ["websocket_support"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "audit_log_viewer",
    name: "Audit Log Viewer",
    description: "Advanced audit trail viewing with filtering and analysis capabilities",
    category: "Admin System",
    subcategory: "Monitoring",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "bulk_user_operations",
    name: "Bulk User Operations",
    description: "Bulk user management actions and CSV import/export capabilities",
    category: "Admin System",
    subcategory: "User Management",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "role_based_permissions",
    name: "Role-based Permissions",
    description: "Granular permission system for different administrative levels",
    category: "Admin System",
    subcategory: "Security",
    enabled: false,
    dependencies: [],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // BANKING & FINANCIAL SERVICES
  {
    id: "multi_currency_support",
    name: "Multi-currency Support",
    description: "Support for multiple currencies with real-time exchange rates",
    category: "Banking",
    subcategory: "Currency",
    enabled: false,
    dependencies: ["exchange_rate_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "automated_savings",
    name: "Automated Savings",
    description: "Automated savings programs with round-up and goal-based saving",
    category: "Banking",
    subcategory: "Savings",
    enabled: false,
    dependencies: ["banking_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "instant_transfers",
    name: "Instant Transfers",
    description: "Real-time money transfers between accounts and users",
    category: "Banking",
    subcategory: "Transfers",
    enabled: false,
    dependencies: ["banking_api", "payment_processor"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // SECURITY & PRIVACY
  {
    id: "two_factor_authentication",
    name: "Two-Factor Authentication",
    description: "Enhanced security with 2FA support for all accounts",
    category: "Security",
    subcategory: "Authentication",
    enabled: false,
    dependencies: ["sms_service", "authenticator_app"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "biometric_authentication",
    name: "Biometric Authentication",
    description: "Fingerprint and face recognition authentication",
    category: "Security",
    subcategory: "Authentication",
    enabled: false,
    dependencies: ["biometric_api"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "advanced_encryption",
    name: "Advanced Encryption",
    description: "End-to-end encryption for all sensitive data and communications",
    category: "Security",
    subcategory: "Encryption",
    enabled: false,
    dependencies: ["encryption_library"],
    conflicts: [],
    requiresRestart: true,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // NOTIFICATIONS & COMMUNICATION
  {
    id: "push_notifications",
    name: "Push Notifications",
    description: "Real-time push notifications for important events",
    category: "Communication",
    subcategory: "Notifications",
    enabled: false,
    dependencies: ["notification_service"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "email_notifications",
    name: "Email Notifications",
    description: "Customizable email notifications for account activities",
    category: "Communication",
    subcategory: "Notifications",
    enabled: false,
    dependencies: ["email_service"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "low",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "sms_notifications",
    name: "SMS Notifications",
    description: "SMS alerts for critical account activities and security events",
    category: "Communication",
    subcategory: "Notifications",
    enabled: false,
    dependencies: ["sms_service"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: false,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },

  // ANALYTICS & REPORTING
  {
    id: "advanced_analytics_dashboard",
    name: "Advanced Analytics Dashboard",
    description: "Comprehensive analytics dashboard with custom metrics",
    category: "Analytics",
    subcategory: "Dashboards",
    enabled: false,
    dependencies: ["analytics_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "custom_reports",
    name: "Custom Reports",
    description: "User-configurable reports with export capabilities",
    category: "Analytics",
    subcategory: "Reporting",
    enabled: false,
    dependencies: ["reporting_engine"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: false,
    premiumFeature: true,
    estimatedImpact: "medium",
    lastModified: new Date(),
    modifiedBy: "system",
  },
  {
    id: "real_time_analytics",
    name: "Real-time Analytics",
    description: "Live analytics with real-time data processing and visualization",
    category: "Analytics",
    subcategory: "Real-time",
    enabled: false,
    dependencies: ["analytics_engine", "websocket_support"],
    conflicts: [],
    requiresRestart: false,
    betaFeature: true,
    premiumFeature: true,
    estimatedImpact: "high",
    lastModified: new Date(),
    modifiedBy: "system",
  },
]

// FEATURE CATEGORIES
export const FEATURE_CATEGORIES: FeatureCategory[] = [
  {
    id: "financial_management",
    name: "Financial Management",
    description: "Core financial features including transactions, payments, and banking",
    icon: "DollarSign",
    color: "emerald",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Financial Management"),
  },
  {
    id: "data_management",
    name: "Data Management",
    description: "Data handling, pagination, search, and organization features",
    icon: "Database",
    color: "blue",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Data Management"),
  },
  {
    id: "holographic_experience",
    name: "Holographic Experience",
    description: "3D visualization, holographic displays, and immersive interfaces",
    icon: "Sparkles",
    color: "purple",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Holographic Experience"),
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    description: "Product marketplace, shopping cart, and e-commerce features",
    icon: "ShoppingCart",
    color: "orange",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "E-Commerce"),
  },
  {
    id: "ar_vr_experience",
    name: "AR/VR Experience",
    description: "Augmented and virtual reality features for immersive experiences",
    icon: "Glasses",
    color: "pink",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "AR/VR Experience"),
  },
  {
    id: "real_estate",
    name: "Real Estate",
    description: "Property listings, real estate marketplace, and investment tools",
    icon: "Home",
    color: "green",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Real Estate"),
  },
  {
    id: "ai_features",
    name: "AI Features",
    description: "Artificial intelligence, machine learning, and automation features",
    icon: "Brain",
    color: "indigo",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "AI Features"),
  },
  {
    id: "legal_compliance",
    name: "Legal & Compliance",
    description: "Legal documents, compliance monitoring, and regulatory features",
    icon: "Scale",
    color: "slate",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Legal & Compliance"),
  },
  {
    id: "ui_ux",
    name: "UI/UX",
    description: "User interface, user experience, and design enhancements",
    icon: "Palette",
    color: "rose",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "UI/UX"),
  },
  {
    id: "investment_tools",
    name: "Investment Tools",
    description: "Portfolio management, trading tools, and investment analytics",
    icon: "TrendingUp",
    color: "cyan",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Investment Tools"),
  },
  {
    id: "gamification",
    name: "Gamification",
    description: "Gaming elements, rewards, progression, and social features",
    icon: "Trophy",
    color: "yellow",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Gamification"),
  },
  {
    id: "business_features",
    name: "Business Features",
    description: "Enterprise features, business tools, and B2B functionality",
    icon: "Building",
    color: "gray",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Business Features"),
  },
  {
    id: "banking",
    name: "Banking",
    description: "Banking services, accounts, transfers, and financial products",
    icon: "CreditCard",
    color: "emerald",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Banking"),
  },
  {
    id: "security",
    name: "Security",
    description: "Authentication, encryption, privacy, and security features",
    icon: "Shield",
    color: "red",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Security"),
  },
  {
    id: "communication",
    name: "Communication",
    description: "Notifications, messaging, and communication features",
    icon: "MessageSquare",
    color: "blue",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Communication"),
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Data analytics, reporting, and business intelligence features",
    icon: "BarChart",
    color: "violet",
    features: SNAPIFI_FEATURE_TOGGLES.filter((f) => f.category === "Analytics"),
  },
]

// FEATURE TOGGLE MANAGER CLASS
export class FeatureToggleManager {
  private features: Map<string, FeatureToggle> = new Map()
  private listeners: Set<(feature: FeatureToggle) => void> = new Set()

  constructor() {
    // Initialize with default features
    SNAPIFI_FEATURE_TOGGLES.forEach((feature) => {
      this.features.set(feature.id, { ...feature })
    })
  }

  // Get all features
  getAllFeatures(): FeatureToggle[] {
    return Array.from(this.features.values())
  }

  // Get features by category
  getFeaturesByCategory(category: string): FeatureToggle[] {
    return this.getAllFeatures().filter((f) => f.category === category)
  }

  // Get enabled features
  getEnabledFeatures(): FeatureToggle[] {
    return this.getAllFeatures().filter((f) => f.enabled)
  }

  // Check if feature is enabled
  isFeatureEnabled(featureId: string): boolean {
    const feature = this.features.get(featureId)
    return feature?.enabled ?? false
  }

  // Toggle feature
  toggleFeature(featureId: string, enabled: boolean, modifiedBy = "user"): boolean {
    const feature = this.features.get(featureId)
    if (!feature) return false

    // Check dependencies
    if (enabled && !this.checkDependencies(feature)) {
      throw new Error(`Cannot enable ${feature.name}: missing dependencies`)
    }

    // Check conflicts
    if (enabled && !this.checkConflicts(feature)) {
      throw new Error(`Cannot enable ${feature.name}: conflicts with other enabled features`)
    }

    // Update feature
    feature.enabled = enabled
    feature.lastModified = new Date()
    feature.modifiedBy = modifiedBy

    // Notify listeners
    this.listeners.forEach((listener) => listener(feature))

    return true
  }

  // Bulk toggle features
  bulkToggleFeatures(featureIds: string[], enabled: boolean, modifiedBy = "user"): void {
    featureIds.forEach((id) => {
      try {
        this.toggleFeature(id, enabled, modifiedBy)
      } catch (error) {
        console.warn(`Failed to toggle feature ${id}:`, error)
      }
    })
  }

  // Enable all features in category
  enableCategoryFeatures(category: string, modifiedBy = "user"): void {
    const categoryFeatures = this.getFeaturesByCategory(category)
    const featureIds = categoryFeatures.map((f) => f.id)
    this.bulkToggleFeatures(featureIds, true, modifiedBy)
  }

  // Disable all features in category
  disableCategoryFeatures(category: string, modifiedBy = "user"): void {
    const categoryFeatures = this.getFeaturesByCategory(category)
    const featureIds = categoryFeatures.map((f) => f.id)
    this.bulkToggleFeatures(featureIds, false, modifiedBy)
  }

  // Check dependencies
  private checkDependencies(feature: FeatureToggle): boolean {
    return feature.dependencies.every((depId) => this.isFeatureEnabled(depId))
  }

  // Check conflicts
  private checkConflicts(feature: FeatureToggle): boolean {
    return !feature.conflicts.some((conflictId) => this.isFeatureEnabled(conflictId))
  }

  // Add change listener
  addChangeListener(listener: (feature: FeatureToggle) => void): void {
    this.listeners.add(listener)
  }

  // Remove change listener
  removeChangeListener(listener: (feature: FeatureToggle) => void): void {
    this.listeners.delete(listener)
  }

  // Export configuration
  exportConfiguration(): string {
    const config = {
      features: this.getAllFeatures(),
      exportDate: new Date().toISOString(),
      version: "1.0.0",
    }
    return JSON.stringify(config, null, 2)
  }

  // Import configuration
  importConfiguration(configJson: string): void {
    try {
      const config = JSON.parse(configJson)
      if (config.features && Array.isArray(config.features)) {
        config.features.forEach((feature: FeatureToggle) => {
          if (this.features.has(feature.id)) {
            this.features.set(feature.id, feature)
          }
        })
      }
    } catch (error) {
      throw new Error("Invalid configuration format")
    }
  }

  // Get feature statistics
  getStatistics() {
    const allFeatures = this.getAllFeatures()
    const enabledFeatures = this.getEnabledFeatures()

    return {
      total: allFeatures.length,
      enabled: enabledFeatures.length,
      disabled: allFeatures.length - enabledFeatures.length,
      betaFeatures: allFeatures.filter((f) => f.betaFeature).length,
      premiumFeatures: allFeatures.filter((f) => f.premiumFeature).length,
      requiresRestart: enabledFeatures.filter((f) => f.requiresRestart).length,
      byCategory: FEATURE_CATEGORIES.map((cat) => ({
        category: cat.name,
        total: cat.features.length,
        enabled: cat.features.filter((f) => this.isFeatureEnabled(f.id)).length,
      })),
    }
  }
}

// Export singleton instance
export const featureToggleManager = new FeatureToggleManager()
