"use client"

import { PaginatedPropertyGrid } from "@/components/ecommerex/paginated-property-grid"
import { HolographicHeader } from "@/components/ecommerex/holographic-header"
import { PropertyComparisonProvider } from "@/contexts/property-comparison-context"

// Enhanced sample real estate data
const properties = [
  {
    id: "1",
    title: "Luxury Quantum Penthouse",
    description: "Stunning penthouse with holographic smart home integration and quantum energy systems",
    price: 4500000,
    monthlyPayment: 18750,
    image: "/properties/quantum-penthouse.jpg",
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 3.5,
    sqft: 3200,
    yearBuilt: 2024,
    rating: 4.9,
    location: "Manhattan, NY",
    status: "For Sale",
    features: ["Smart Home", "Quantum Energy", "Rooftop Garden", "City Views"],
    isHolographic: true,
    has360View: true,
    images360: [
      "/properties/360/penthouse-001.jpg",
      "/properties/360/penthouse-002.jpg",
      "/properties/360/penthouse-003.jpg",
      "/properties/360/penthouse-004.jpg",
      "/properties/360/penthouse-005.jpg",
      "/properties/360/penthouse-006.jpg",
      "/properties/360/penthouse-007.jpg",
      "/properties/360/penthouse-008.jpg",
    ],
    holographicFeatures: ["Holographic Displays", "Neural Interface Controls", "Quantum Security", "AI Concierge"],
    daysOnMarket: 12,
    pricePerSqft: 1406,
  },
  {
    id: "2",
    title: "Modern Family Home",
    description: "Beautiful family home with open concept design and premium finishes throughout",
    price: 850000,
    monthlyPayment: 3542,
    image: "/properties/modern-family-home.jpg",
    type: "Single Family",
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2800,
    yearBuilt: 2021,
    rating: 4.6,
    location: "Austin, TX",
    status: "For Sale",
    features: ["Open Concept", "Premium Finishes", "Large Backyard", "Garage"],
    isHolographic: false,
    has360View: true,
    images360: [
      "/properties/360/family-home-001.jpg",
      "/properties/360/family-home-002.jpg",
      "/properties/360/family-home-003.jpg",
      "/properties/360/family-home-004.jpg",
      "/properties/360/family-home-005.jpg",
      "/properties/360/family-home-006.jpg",
      "/properties/360/family-home-007.jpg",
      "/properties/360/family-home-008.jpg",
    ],
    daysOnMarket: 28,
    pricePerSqft: 304,
  },
  {
    id: "3",
    title: "HoloLoft Downtown",
    description: "Cutting-edge loft with holographic entertainment systems and futuristic amenities",
    price: 1200000,
    monthlyPayment: 5000,
    image: "/properties/holo-loft.jpg",
    type: "Loft",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1800,
    yearBuilt: 2024,
    rating: 4.8,
    location: "San Francisco, CA",
    status: "For Sale",
    features: ["Holographic Entertainment", "Smart Appliances", "Floor-to-Ceiling Windows", "Rooftop Access"],
    isHolographic: true,
    has360View: true,
    images360: [
      "/properties/360/loft-001.jpg",
      "/properties/360/loft-002.jpg",
      "/properties/360/loft-003.jpg",
      "/properties/360/loft-004.jpg",
      "/properties/360/loft-005.jpg",
      "/properties/360/loft-006.jpg",
      "/properties/360/loft-007.jpg",
      "/properties/360/loft-008.jpg",
    ],
    holographicFeatures: ["Holographic Entertainment", "AI Assistant", "Smart Glass", "Neural Controls"],
    daysOnMarket: 7,
    pricePerSqft: 667,
  },
  {
    id: "4",
    title: "Cozy Suburban Townhouse",
    description: "Charming townhouse with modern updates and private patio in quiet neighborhood",
    price: 520000,
    monthlyPayment: 2167,
    image: "/properties/suburban-townhouse.jpg",
    type: "Townhouse",
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1600,
    yearBuilt: 2018,
    rating: 4.4,
    location: "Denver, CO",
    status: "For Sale",
    features: ["Private Patio", "Updated Kitchen", "Garage", "Quiet Neighborhood"],
    isHolographic: false,
    has360View: false,
    daysOnMarket: 45,
    pricePerSqft: 325,
  },
  {
    id: "5",
    title: "Quantum Smart Condo",
    description: "Ultra-modern condo with quantum computing integration and holographic lifestyle management",
    price: 950000,
    monthlyPayment: 3958,
    image: "/properties/quantum-condo.jpg",
    type: "Condo",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2000,
    yearBuilt: 2024,
    rating: 4.9,
    location: "Seattle, WA",
    status: "For Sale",
    features: ["Quantum Computing", "Smart Everything", "City Views", "Luxury Amenities"],
    isHolographic: true,
    has360View: true,
    images360: [
      "/properties/360/condo-001.jpg",
      "/properties/360/condo-002.jpg",
      "/properties/360/condo-003.jpg",
      "/properties/360/condo-004.jpg",
      "/properties/360/condo-005.jpg",
      "/properties/360/condo-006.jpg",
      "/properties/360/condo-007.jpg",
      "/properties/360/condo-008.jpg",
    ],
    holographicFeatures: ["Quantum Processing", "Holographic Management", "AI Security", "Neural Interfaces"],
    daysOnMarket: 3,
    pricePerSqft: 475,
  },
  {
    id: "6",
    title: "Beachfront Villa",
    description: "Stunning beachfront villa with panoramic ocean views and private beach access",
    price: 2800000,
    monthlyPayment: 11667,
    image: "/properties/beachfront-villa.jpg",
    type: "Villa",
    bedrooms: 6,
    bathrooms: 4,
    sqft: 4500,
    yearBuilt: 2020,
    rating: 4.7,
    location: "Malibu, CA",
    status: "For Sale",
    features: ["Ocean Views", "Private Beach", "Infinity Pool", "Wine Cellar"],
    isHolographic: false,
    has360View: true,
    images360: [
      "/properties/360/villa-001.jpg",
      "/properties/360/villa-002.jpg",
      "/properties/360/villa-003.jpg",
      "/properties/360/villa-004.jpg",
      "/properties/360/villa-005.jpg",
      "/properties/360/villa-006.jpg",
      "/properties/360/villa-007.jpg",
      "/properties/360/villa-008.jpg",
    ],
    daysOnMarket: 62,
    pricePerSqft: 622,
  },
]

export function RealEstateMarketplace() {
  return (
    <PropertyComparisonProvider>
      <div className="container mx-auto p-4 space-y-8">
        <HolographicHeader
          title="DOMUS IMPERIUM MERCATUS"
          subtitle="Discover premium properties with cutting-edge holographic technology and immersive virtual tours"
        />

        <PaginatedPropertyGrid properties={properties} itemsPerPage={6} />
      </div>
    </PropertyComparisonProvider>
  )
}
