export default ({ router }) => {
  const redirects = [
    { path: '/wallet-api/', redirect: '/guides/wallet/' },
    { path: '/wallet-api.html', redirect: '/guides/wallet/' },
    { path: '/chainlink-integration/', redirect: '/guides/chainlink-integration/' },
    { path: '/chainlink-integration.html', redirect: '/guides/chainlink-integration/' },
    { path: '/distributed-programming/', redirect: '/guides/js-programming/' },
    { path: '/distributed-programming.html', redirect: '/guides/js-programming/' },
    { path: '/getting-started/agoric-cli-guide/', redirect: '/guides/agoric-cli/' },
    { path: '/getting-started/agoric-cli-guide.html', redirect: '/guides/agoric-cli/' },
    { path: '/guides/js-programming/ses/ses-guide.html', redirect: 'https://github.com/endojs/endo/blob/HEAD/packages/ses/docs/guide.md' },
    { path: '/guides/js-programming/ses/ses-reference.html', redirect: 'https://github.com/endojs/endo/blob/HEAD/packages/ses/docs/reference.md' },
    { path: '/guides/js-programming/ses/lockdown.html', redirect: 'https://github.com/endojs/endo/blob/HEAD/packages/ses/docs/lockdown.md' },
    { path: '/getting-started/before-using-agoric.html', redirect: '/conceptual/getting-started/' },
    { path: '/getting-started/start-a-project.html', redirect: '/conceptual/getting-started/start-a-project.md' },
    { path: '/guides/agoric-cli/commands.html', redirect: '/conceptual/agoric-cli/' },
    { path: '/dapps/', redirect: '/conceptual/dapps/' },
    { path: '/ertp/guide/', redirect: '/conceptual/ertp/' },
    { path: '/ertp/guide/amounts.html', redirect: '/conceptual/ertp/amounts.md' },
    { path: '/guides/js-programming/', redirect: '/conceptual/js-programming/' },
    { path: '/guides/js-programming/hardened-js.html', redirect: '/conceptual/js-programming/hardened-js.md' },
    { path: '/platform/', redirect: '/conceptual/platform/' },
    { path: '/guides/wallet/', redirect: '/conceptual/wallet/' },
    { path: '/guides/wallet/ui.html', redirect: '/conceptual/wallet/ui.md' },
    { path: '/zoe/guide/', redirect: '/conceptual/zoe/' },
    { path: '/getting-started/intro-zoe.html', redirect: '/conceptual/zoe/offer-enforcement.md' },
    { path: '/zoe/guide/offer-safety.html', redirect: '/conceptual/zoe/offer-safety.md' },
    { path: '/zoe/guide/contracts/', redirect: '/conceptual/zoe/contracts/' },
    { path: '/zoe/guide/contracts/oracle.html', redirect: '/conceptual/zoe/contracts/oracle.md' },
    { path: '/guides/chainlink-integration.html', redirect: '/conceptual/chainlink-integration.md' },
    { path: '/ertp/api/', redirect: '/reference/ertp-api/' },
    { path: '/ertp/api/issuer.html', redirect: '/reference/ertp-api/issuer.md' },
    { path: '/repl/', redirect: '/reference/repl/' },
    { path: '/repl/timerServices.html', redirect: '/reference/repl/timerServices.md' },
    { path: '/guides/wallet/api.html', redirect: '/reference/wallet-api.md' },
    { path: '/zoe/api/', redirect: '/reference/zoe-api/' },
    { path: '/zoe/api/zoe.html', redirect: '/reference/zoe-api/zoe.md' },
  ];
  redirects.forEach(config => router.addRoute(config));
} 
