sequenceDiagram
  autonumber

  box aqua
  actor A as Alice
  end

  box darksalmon
  participant Zoe
  end

  box skyblue Contract
  participant C as offer-up.contract
  end

    Zoe--)C: tradeHandler(buyerSeat)
    activate C
    C--)C: check proposal
    C--)Zoe: mintGains(want)
    deactivate C
    activate Zoe
    Zoe--)-C: tmp seat

    C--)Zoe: atomicRearrange(...)

    Zoe--)Zoe: check offer safety

    C--)Zoe: buyerSeat.exit(true)