sequenceDiagram
  autonumber

  box aqua
  actor A as Alice
  end

  box darksalmon
  participant Zoe
  end

  box skyblue Contract
  participant C as offer-up.contract
  end

    A-)+Zoe: E(seat).getPayout('Items')
    Note over Zoe: ... many steps above ...
    Zoe--)-A: itemsPayment
    A-)+Zoe: E(issuers.Items).getAmountOf(itemsPayment)
    Zoe--)-A: { brand: Item brand,<br> value: [['map', 1n], ['scroll', 1n]]
