sequenceDiagram
  autonumber

  box aqua
  actor A as Alice
  end

  box darksalmon
  participant Zoe
  end

  box skyblue Contract
  participant C as offer-up.contract
  end

    A-)C: makeTradeInvitation()
    activate C
    C--)Zoe: makeInvitation(tradeHandler, ...)
    deactivate C
    activate Zoe
    Zoe--)-C: invitation
    activate C
    C--)A: Invitation toJoin
    deactivate C
    A-)+Zoe: offer(toJoin, proposal, { Price })

    Zoe--)Zoe: escrow Price pmt

    Zoe--)-C: tradeHandler(buyerSeat)
