sequenceDiagram
  autonumber

  box aqua
  actor A as Alice
  end

  box darksalmon
  participant Zoe
  end

  box skyblue Contract Instance
  participant C as gameAssetContract
  end

    A-)Zoe: getPublicFacet(instance)
    A-)+Zoe: getTerms(instance)
    Zoe--)-A: { issuers, brands, joinPrice }
