name: Test the build

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
 push:
   branches: [master]
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        yarn install
        yarn docs:build
  
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: main/.vuepress/dist
        extra: --ignore_re r'\ADuplicate ID "outbound-link-title".*'

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en

    - name: Spell check
      run: |
        python -m pyspelling
