name: Check Markdown links
# on: 
#   schedule:
#     - cron: '*/30 * * * *'

# run CI on pushes to master, and on all PRs (even the ones that target other
# branches)

on:
 push:
   branches: [master]
 pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.7
        with:
          use-quiet-mode: 'yes'
          folder-path: 'main'
          config-file: 'mlc-config.json'
